name: NUnit Tests

on: [push, pull_request]

jobs:
 build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build LabaTest3 project
      run: dotnet build --no-restore --configuration Release ./LabaTest3/LabaTest3.csproj

    - name: Build NUnitTest project
      run: dotnet build --no-restore --configuration Release ./NUnitTest/NUnitTest.csproj

    - name: Test LabaTest3 project
      run: dotnet test --no-build --verbosity normal --logger trx --results-directory ./TestResults ./LabaTest3/LabaTest3.csproj

    - name: Test NUnitTest project
      run: dotnet test --no-build --verbosity normal --logger trx --results-directory ./TestResults ./NUnitTest/NUnitTest.csproj
